# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages

jobs:
  include:
    - os: linux
      r: devel
    - os: linux
      r: oldrel
    - os: linux
      r: release
      env:
        - BUILD_WWW_HERE=true
    - os: osx
      r: oldrel
    - os: osx
      r: release

# For automatic deploy of the website
before_deploy: Rscript -e 'remotes::install_cran("pkgdown")'
deploy:
  provider: script
  script: Rscript -e 'pkgdown::deploy_site_github()'
  skip_cleanup: true
  on:
    branch: master
    condition: $BUILD_WWW_HERE = linux

