name: R CI release

on: [push, pull_request]

jobs:
  build:
    runs-on: Ubuntu-latest
    strategy:
      matrix:
        include:
        - name: latest
          cntr: uscbiostats/slurmr:rcmdcheck

    steps:
      - uses: actions/checkout@v2

      - name: Setting up the environment
        run: docker pull ${{ matrix.cntr }}
          
      - name: Running the check
        run: |
          cd docker
          make check

