name: R CI release

on: [push, pull_request]

jobs:
  build:
    runs-on: Ubuntu-latest
    strategy:
      matrix:
        include:
        - name: latest
          cntr: uscbiostats/slurmr:rcmdcheck

    steps:
      - uses: actions/checkout@v2

      - name: Setting up the environment
        run: docker pull ${{ matrix.cntr }}

      - name: Running the check
        run: |
          cd docker
          make check

      - name: Coverage
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: |
          cd docker
          docker run \
		        -e GITHUB_ACTION=$GITHUB_ACTION \
        		-e GITHUB_REPOSITORY=$GITHUB_REPOSITORY \
            -e GITHUB_REF=$GITHUB_REF \
            -e GITHUB_HEAD_REF=$GITHUB_HEAD_REF \
            -e GITHUB_RUN_ID=$GITHUB_RUN_ID \
            -e GITHUB_SHA=$GITHUB_SHA \
            -e CODECOV_TOKEN=$CODECOV_TOKEN \
        		--detach --publish 10022:22 \
        		-v$(PWD)/..:/home/xenon/slurmR -w/home/xenon \
        		uscbiostats/slurmr:interactive
	       	echo "Waiting a few seconds..." & sleep 5 && \
		        ssh -p 10022 -i id_rsa xenon@localhost \
		        'cd /home/slurmr-test/ && Rscript -e "covr::codecov(\"/home/xenon/slurmR\", quiet = FALSE)"'

